### ISSUE TITLE
missing license file

### ISSUE THREAD

**Issue by glycerine** [JamesDunne/sslmux#2]
Hi James,

I'd like to use your library as a part of a project I'm writing in Go, but it doesn't appear you have licensed it for anyone else to use.

Could you put an MIT or BSD license on it?

Thanks!

Jason

**Comment by JamesDunne** [comment]
Sure thing! Consider it BSD licensed for now.

Out of curiosity, what is your project? You can email me details if you want to keep it private. Would love to hear!
